require: rubocop-rspec
Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/support/**/*'
    - 'spec/*_helper.rb'
    - 'bin/{rails,rake}'
RSpec/ReturnFromStub:
  EnforcedStyle: block
RSpec/ImplicitExpect:
  EnforcedStyle: should
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ExampleWording:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**/*'
    - '**/*.rake'
Style/Documentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
