AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/support/**/*'
    - 'bin/{rails,rake}'
Metrics/LineLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
