language: ruby
rvm:
  - 2.1.3
before_script:
  - psql -c 'create database rails_base_test;' -U postgres
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  code_climate:
    repo_token: e92bc20eda188adfb37ce135c34b57bbcce993a76f63385137c9aa5dea1fa1f5 
