docker: &docker
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *docker
  database: rails_base_dev

test:
  <<: *docker
  host: localhost # to run specs outside of docker
  database: rails_base_test

production:
  adapter: postgresql
  database: rails_base_pro