development:
  adapter: postgresql
  host: localhost
  database: rails_base_dev

test:
  adapter: postgresql
  database: rails_base_test
  host: localhost

production:
  adapter: postgresql
  host: localhost
  database: rails_base_pro