docker: &docker
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: postgres
  port: 5432

development:
  <<: *docker
  database: rails_base_dev

test:
  <<: *docker
  database: rails_base_dev

production:
  adapter: postgresql
  database: rails_base_pro